### ISSUE TITLE
Add you to my RSS feed?

### ISSUE THREAD

**Issue by MKGitHub** [ustwo/formvalidator-swift#12]
Hi,
I would like to add "formvalidator-swift" to my RSS feed – is that okay?
https://github.com/MKGitHub/TheSwiftSweets

**Comment by ghost** [comment]
@MKGitHub By all means, you may link to the repo in your RSS feed. :smile:

If you have any comments, questions, or concerns about the library don't hesitate to open an issue (or better yet an accompanying pull request!).
