### ISSUE TITLE
Can't assign validatorDelegate to ValidatorTextField

### ISSUE THREAD

**Issue by nickfedoroff** [ustwo/formvalidator-swift#19]
### Description

When I attempt to assign a `validatorDelegate` to a `ValidatorTextField` I get a compiler error: "Cannot assign to property: 'validatorDelegate' is a get-only property"

### Steps to Reproduce

1. Create a `ValidatorTextField`.
2. Assign `validatorDelegate`. `field.validatorDelegate = self`
3. Xcode build error.

### Expected Result

I should be able to assign my view controller as a delegate of the field.

### Actual Result

Build error.

### Version Information

The current version I am using is:

- Xcode: 8.1 
- iOS/tvOS: 10.0
- FormValidator: 1.0

### Other Information

> Add logs, screenshots, etc. that will help in debugging the issue.

**Comment by nickfedoroff** [comment]
Disregard. I discovered the `setValidatorDelegate` method through experimentation. Perhaps this function should be documented.

**Comment by ghost** [comment]
@nickfedoroff Thanks for the feedback. I agree that this should be better documented both in the code and in the example!
