### ISSUE TITLE
Optional validator

### ISSUE THREAD

**Issue by markst** [ustwo/formvalidator-swift#62]
I've created a from which conforms to `Form` protocol but I'd like some validations to only occur if a field is present.

I haven't figured whether this is already possible, currently I've created my own validator `OptionalValidator`. As an example:

```swift
public init(condition: Condition = PresentCondition(), conditions: [Condition]) {
    self.condition = condition
    self.conditions = conditions
}

// MARK: - Validator

public func checkConditions(_ text: String?) -> [Condition]? {
    if condition.check(text) {
        let violations = conditions.filter { !($0.check(text)) }
        return violations
    }
    return nil
}
```

**Comment by ghost** [comment]
You can do this with the pre-existing validators, but it's non-trivial. You'd have to do Not + Present conditions combined with an Or condition to your main condition that has your main validation check. 😅 

This might be a good addition to the core set of conditions/validators to make this type of a setup easier. If you'd like to take a stab at it, we'd welcome a PR!
